### PR TITLE
Add multiplayer cursors and cursor chat

### PR DESCRIPTION
**Pull request by reesericci**
This PR adds multiplayer cursors and cursor chat support through the use of Y.js, action cable, and https://github.com/obl-ong/cursor-chat-actioncable (forked from jackyzha0/cursor-chat)

This only adds multiplayer cursors to anything using the domain layout, that way it's scoped to a domain, and doesn't appear on every page. This also doesn't add synced text input, so the experience isn't seamless.

### CODE REVIEW

**Comment by reesericci** [comment]
Related to #29

**Comment by ajs256** [comment]
What's the point of this without shared domains?

**Comment by reesericci** [comment]
If you share an account through say a team@ email or otherwise, it also lays the groundwork for full shared domains in 2.0

**Review by ajs256 — APPROVED** [review]
looks alright, haven't tested

**Comment by reesericci** [comment]
I think we should test something like this

**Review by polypixeldev — APPROVED** [review]
LGTM

**Pull request merged**
