### PR TITLE
Add CSP

### PR DESCRIPTION
**Pull request by reesericci**
This PR makes the necessary changes to add a decent content security policy (with nonces & unsafe-inline for style attributes unfortunately).

### CODE REVIEW

**Comment by reesericci** [comment]
image

However this incorrectly determines that we don't use unsafe-inline, as shown a little further down the page

https://observatory.mozilla.org/analyze/admin.obl.ong

**Review by polypixeldev — COMMENTED** [review]
Scripts seem to be being blocked with the CSP - I see a lot of CSP errors in the browser console, and if I change the config to actually enforce the CSP scripts such as the cursor chat script are being blocked.

**Comment by reesericci** [comment]
Can you check that the CSP errors aren't coming from extensions? Also, if you open up the network tag can you get the specific URLs being blocked

**Review by polypixeldev — APPROVED** [review]
Odd, I'm not seeing the errors anymore. I'll blame caching. LGTM!

**Pull request merged**
